name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          switches: -avz --delete  # Opciones de rsync
          path: ./  # Carpeta a sincronizar
          remote_path: /var/www/html/ # Ruta en el servidor
          remote_host: ${{ secrets.REMOTE_HOST }}  # IP del servidor
          remote_user: ${{ secrets.USER }}  # Usuario SSH en el servidor
